### ISSUE TITLE
md-total is passed to self.pages as string so function return total of items not total of page

### ISSUE THREAD

**Issue by sam-g-roberts** [daniel-nagy/md-data-table#360]
In this function

self.total is always equal to a string so the return is incorrect, needs to be parsed as a float. 

self.pages = function () {
      return isPositive(self.total) ? Math.ceil(self.total / (isPositive(self.limit) ? 1 : self.limit)) : 1;
    };

**Comment by sam-g-roberts** [comment]
I can see that you've fixed this on master in github but i cant seem to get your fix when installing through bower, any ideas?

**Comment by daniel-nagy** [comment]
Hmm... I just pulled it down from bower and it pull the correct version. When I fixed the `isPositive` method, to use `parseInt`, I overwrote the previous release so I think this is a problem with Bower's cache being stale.

Can you try the following and report back.

1. Remove the component from the `bower_components` directory and then reinstall. I have a feeling it is looking and seeing you already have the latest version so it doesn't update.

   ```
   rm -r bower_components/angular-material-data-table
   bower install
   ```

2. Try cleaning the cache. If you run `bower cache list` you should see `v0.10.4` of the data table

   ```
   bower cache list
   ...
   angular-material-data-table=https://github.com/daniel-nagy/md-data-table.git#0.10.4
   ...
   
   bower cache clean angular-material-data-table
   ```

If this is the case I will most likely make another release because I'm sure other people will be effected by this and not know what to do.

**Comment by sam-g-roberts** [comment]
Hi Daniel. That is indeed what i see. I imagine your right and another release is necessary.

Thanks for getting back to me so quickly

**Comment by sam-g-roberts** [comment]
@daniel-nagy any idea when you'll be able to do a new release? I still cant get your new code to pull down even with the steps above and deleting and reinstalling the package

**Comment by daniel-nagy** [comment]
I released a new version a few days ago, should be `v0.10.5`.
